const { ipcRenderer } = require('electron');
let state;
const $ = id => document.getElementById(id);
const bytes = n => n ? `${(n / 1024 / 1024).toFixed(n > 1024 * 1024 * 1024 ? 1 : 0)} ${n > 1024 * 1024 * 1024 ? 'GB' : 'MB'}` : 'Size unknown';
function render(next) { state = next; $('folder-label').textContent = state.config.downloadDir; $('download-folder').value = state.config.downloadDir; $('download-list').innerHTML = state.downloads.length ? state.downloads.map(item => `<article class="row"><div><div class="title">${escapeHtml(item.name)}</div><div class="metadata">${item.status} · ${bytes(item.downloadedBytes)} of ${bytes(item.totalBytes)} · ${item.peers} peers</div><div class="progress"><span style="width:${item.progress}%"></span></div></div><button data-toggle="${item.id}">${item.status === 'paused' ? 'Resume' : 'Pause'}</button></article>`).join('') : '<p class="muted">No active downloads yet.</p>'; document.querySelectorAll('[data-toggle]').forEach(button => button.onclick = () => ipcRenderer.invoke('torlink:toggle', button.dataset.toggle)); }
function escapeHtml(text) { const el = document.createElement('div'); el.textContent = text; return el.innerHTML; }
document.querySelectorAll('.nav').forEach(button => button.onclick = () => { document.querySelectorAll('.nav,.view').forEach(el => el.classList.remove('active')); button.classList.add('active'); $(button.dataset.view).classList.add('active'); });
$('search-form').onsubmit = async event => { event.preventDefault(); const query = $('query').value.trim(); if (!query) return; $('search-status').textContent = 'Searching…'; $('results').innerHTML = ''; const {results, errors} = await ipcRenderer.invoke('torlink:search', query); $('search-status').textContent = `${results.length} results${errors.length ? ` · ${errors.join(', ')}` : ''}`; $('results').innerHTML = results.map((r, i) => `<article class="row"><div><div class="title">${escapeHtml(r.name)}</div><div class="metadata">${r.source} · ${bytes(r.sizeBytes)} · ${r.seeders || 'unknown'} seeders</div></div><button data-result="${i}">Download</button></article>`).join('') || '<p class="muted">No results found.</p>'; document.querySelectorAll('[data-result]').forEach(button => button.onclick = () => ipcRenderer.invoke('torlink:add', results[button.dataset.result])); };
$('open-folder').onclick = () => ipcRenderer.invoke('torlink:open-folder'); $('refresh').onclick = () => ipcRenderer.invoke('torlink:state').then(render); $('browse-folder').onclick = () => ipcRenderer.invoke('torlink:choose-folder').then(render); $('save-folder').onclick = async () => { try { render(await ipcRenderer.invoke('torlink:set-folder', $('download-folder').value)); $('save-status').textContent = 'Saved.'; } catch (error) { $('save-status').textContent = error.message; } }; ipcRenderer.on('torlink:state', (_, next) => render(next)); ipcRenderer.invoke('torlink:state').then(render);
